language: node_js

node_js: 12

before_script: npm run prepublishOnly

script: ""

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  provider: pages
  skip_cleanup: true
